# Generated by Django 4.0.1 on 2022-01-23 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
